name: bebop-builder

on:
  push:
    paths:
    - 'app/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-to-github-cr:
    name: push image to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: authenticate to gh container registry 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & push image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true 
          tags: ghcr.io/${{ github.repository }}:latest
